import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import { FridgesProvider } from "@/context/FridgesContext";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" data-google-analytics-opt-out="">
            <body className={`${inter.className}`}>
                <FridgesProvider>
                    {/*<Suspense>*/}
                    <div className="container">{children}</div>
                    {/*</Suspense>*/}
                </FridgesProvider>
            </body>
        </html>
    );
}
